<select class="form-control" id="formularioTipoOrigen" onchange="cargarConfiguracionTipo('<?php echo $_POST['tablaActual'] ?>')">
    <option value="">selecciones origen</option>
    <option value="algoritmosDate">Algoritmos Date</option>
    <option value="algoritmosTime">Algoritmos DateTime</option>
    <option value="algoritmosTime">Algoritmos Time</option>
</select>
<input type="hidden" value="indirecto" id="directo">