<div class="form-group">
    <div class="input-append date form_datetime" data-date="2013-02-21T15:25:00Z">
        <input class="form-control" type="text" value="">
        <span class="add-on"><i class="icon-remove"></i></span>
        <span class="add-on"><i class="icon-calendar"></i></span>
    </div>
    <div class="form-group">
        <label class="control-label" for="fechaInicial">fecha inicial</label>
        <input type="text" name="fechaInicial" id="fechaInicial" class="input-sm form-control" placeholder="fecha inicial"/>
    </div>
    <div class="form-group">
        <label class="control-label" for="fechaFinal">fecha final</label>
        <input type="text" name="fechaFinal" id="fechaFinal" class="input-sm form-control col-sm-4" placeholder="fecha final"/>
    </div>
</div>

<div>
    <input id="repeat" name="repeat" type="checkbox" title="Aleatorio">
    <label for="repeat">Repetido</label>
</div>
<button class="btn btn-success btn-sm">guardar</button>