<div class="">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 well full-with">
    <?php
    $tablas->printTables();
     $resultadoPT=  $tablas->printTables();
        $contador=1;
        while ($regPT = pg_fetch_assoc($resultadoPT)) {
           echo '<div class="panel panel-primary col-lg-12">
                    <button class="btn btn-link" id="boton'.$contador.'" onclick="mostrarOcultar('.$contador.',\''.$regPT['tablename'].'\');">'.$regPT['tablename'].'</button>
                    <div class="well" id="tabla'.$contador.'" style="display: none">
                       <table class="table table-hover">
                       <tr><th>name</th><th>key</th><th>null</th><th>type</th><th>estado</th></tr>
                      '.$tablas->printDetalleTable($regPT['tablename']).'
                       </table>
                    </div>
                 </div>';
           $contador=$contador+1;
        }
    ?>
    </div>
    <div class="panel panel-success col-lg-6 col-md-6 col-sm-6 col-xs-6 navbar navbar-right" id="formularioConfiguracion">
       <div id="NombreTabla" class="h3 alert alert-success"></div>
       <div id="divtabla" class="well">

       </div>
    </div>
</div>
