<?php
?>
<form  action="javascript:guardarConfiguracion()" class="form" id="formConfiguracion">
   <span class="badge bg-info">cantidad de datos a generar  para la tabla <span class="badge bg-inverse"><?php echo $_POST['tablaactual']; ?></span></span>
   <input type="text" name="numerodatos" id="numerodatos" placeholder="Cantidad de datos" class="form-control input-sm validate[required]"/>
   <div id="tablaCampo">
        selecciona un atributo
   </div>
   <div id="formularioPersonalizado">
        selecciona fuente
   </div>
</form>
