<?php
?>
<form  action="javascript:guardarConfiguracion()" class="form" id="formConfig">
   <span>cantidad de datos a generar  para la tabla <b><?php echo $_POST['tablaactual']; ?></b></span>
   <input type="text" name="numerodatos" id="numerodatos" placeholder="numero de datos" class="form-control input-sm"/>
   <div id="tablaCampo">
        selecciona un atributo
   </div>
   <div id="formularioPersonalizado">
        selecciona fuente
   </div>
   <button class="btn btn-success btn-sm">guardar</button>
</form>
