<div class="panel panel-body nuevo">
    <a class="glyphicon glyphicon-plus-sign btn btn-success btn-lg" href="index.php?<?php echo ACTION ?>=nuevo">
        New
    </a>
</div>
<?php
$directorio=$proyectos->actionMostrarProyectos();
while ($archivo = readdir($directorio)){
    if (is_dir($archivo)){
    }
    else {
        ?>
        <div class="col-xs-3 well proyecto">
            <?php
            echo "<a href='index.php?".ACTION."=load&".PROYECTO."=".$archivo."' class='panel'>".$archivo."</a>";
            ?>
            <a href="controller/removeProjectController.php?<?php echo REMOVE_PROYECTO ?>=<?php echo $archivo?>" class="btn btn-sm btn-danger navbar-right"><span class="glyphicon glyphicon-remove"></span></a>
        </div>
    <?php
    }
}
?>