<div class="">
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 well full-with">
        <?php
        echo "<h2>Proyecto : " . $_GET[PROYECTO] . "</h2>";
        echo '<input type="hidden" value="' . $_GET[PROYECTO] . '" id="project">';
        $resultadoPT = $loadTablas->getTablesAndReferencesLoad();
        for ($contador = 1; $contador <= sizeof($resultadoPT); $contador++) {
            echo '<div class="panel panel-primary nivel' . $resultadoPT[$contador - 1]['nivel'] . ' col-lg-12">
                    <button class="btn fa fa-th nivelPanel' . $resultadoPT[$contador - 1]['nivel'] . '"> ' . $resultadoPT[$contador - 1]['nivel'] . '</button>
                    <button class="btn btn-link" id="boton' . $contador . '" onclick="mostrarOcultar(' . $contador . ',\'' . $resultadoPT[$contador - 1]['tablename'] . '\');">' . $resultadoPT[$contador - 1]['tablename'] . '</button>
                    <div class="well" id="tabla' . $contador . '" style="display: none">
                       <table class="table table-hover">
                       <tr><th>name</th><th>key</th><th>null</th><th>type</th><th>estado</th></tr>
                      ' . printDetalleTable($resultadoPT[$contador - 1]['tablename']) . '
                       </table>
                    </div>
                 </div>';
        }
        ?>
    </div>
    <div class="panel panel-success arriba col-lg-offset-6 col-md-offset-6 col-sm-offset-6 col-xs-offset-6 col-lg-5 col-md-5 col-sm-5 col-xs-5" id="formularioConfiguracion">
        <div id="NombreTabla" class="h3 alert alert-success"></div>
        <div id="divtabla" class="well">

        </div>
        <?php

        function printDetalleTable($tabla){
            $var=null;
            $loadDetalle = new loadModel($_GET[PROYECTO]);
            $resultadoPDT = $loadDetalle->printDetalleTableLoad($tabla);
            /*
             *  "column_name": "cod_rol_para, cod_usu_para",
                "data_type": "FOREIGN",
                "character_maximum_length": "",
                "es_foranea": "true",
                "referencian": "cod_rol_para, cod_usu_para",
                "tabla": "usuario",
                "referenciados": "cod_rol, cod_usu",
                "numeric_precision": "",
                "is_nullable": "NO",
                "constraint_type": "foraneas"
             * */
            for ($contador = 0; $contador < sizeof($resultadoPDT); $contador++) {
                $var .="<tr>"
                    . "<td><button class='btn btn-link'onclick=\"
                                              cargarPanelConfiguracion('" .$tabla . "','"
                                                                          .$resultadoPDT[$contador]['column_name'] . "','"
                                                                          .$resultadoPDT[$contador]['data_type']."','"
                                                                          .$resultadoPDT[$contador]['es_foranea']."','"
                                                                          .$resultadoPDT[$contador]['referencian']."','"
                                                                          .$resultadoPDT[$contador]['tabla']."','"
                                                                          .$resultadoPDT[$contador]['referenciados']."','"
                                                                          .$resultadoPDT[$contador]['is_nullable']."','"
                                                                          .$resultadoPDT[$contador]['constraint_type']."')\">" . $resultadoPDT[$contador]['column_name'] . "</button></td>"
                    . "<td>" . isPrimaryKey($resultadoPDT[$contador]['constraint_type']) . "</td>"
                    . "<td>" . $resultadoPDT[$contador]['is_nullable'] . "</td>"
                    . "<td>" . $resultadoPDT[$contador]['data_type'] . "</td>"
                    . "<td class='indicador'>".statusColumn($loadDetalle->getStatusColumnLoad($tabla,$resultadoPDT[$contador]['column_name']))."</td>"
                    . "</tr>";
            }
            return $var;
        }
        function statusColumn($estado){
            if($estado=="existe"){
                return "<span style='color: green' class='glyphicon glyphicon-ok-circle'></span>";
            }
            else{
                return "<span style='color: red' class='glyphicon glyphicon-remove-circle'></span>";
            }
        }
        function isPrimaryKey($cadena){
            if (trim($cadena) != null) {
                return "<span class='glyphicon glyphicon-flash h6' style='color: orange'></span>";
            } else {
                return "";
            }
        }

        ?>
    </div>
</div>
