<div class="col-lg-7 col-md-8 col-sm-10 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-1">
    <?php
    switch($_GET['msm']){
        case 1:
            ?>
            <div class="alert alert-danger">
                ya existe el nomnre del proyecto
            </div>
        <?php
        case 2:
            ?>
            <div class="alert alert-danger">
                Error en los datos procure que los datos ingresados sean correctos...
            </div>
        <?php
    }
    ?>
    <form class="form col-lg-12  well" action="controller/crearController.php" id="formulariotestconn" method="POST">
        <div>
            <span>Nombre</span>
            <input class="form-control input-sm validate[required,custom[onlyLetterNumber]]" type="text" name="<?php echo NOMBRE_PROYECTO ?>" id="<?php echo NOMBRE_PROYECTO ?>"/>
        </div>
        <div class="">
            <span class="">SGBD</span>
            <select class="form-control input-sm validate[required]" name="basededatos" id="basededatos">
                <option value="">Seleccione un gestor</option>
                <option value="PostgreSQL">PostgreSQL</option>
            </select>
        </div>
        <div class="">
            <span class="">base de datos</span>
            <input type="text" class="form-control input-sm validate[required,custom[onlyLetterNumber]]" name="nombrebasedatos" id="nombrebasedatos"/>
        </div>
        <div class="">
            <span class="">host</span>
            <input type="text" class="form-control input-sm validate[required]" name="host" id="host"/>
        </div>
        <div class="">
            <span class="">puerto</span>
            <input type="text" class="form-control input-sm validate[required,custom[onlyLetterNumber]]" name="puerto" id="puerto" value="5432"/>
        </div>
        <div class="">
            <span class="glyphicon glyphicon-user">usuario</span>
            <input type="text" class="form-control input-sm validate[required,custom[onlyLetterNumber]]" name="usuario" id="usuario"/>
        </div>
        <div class="">
            <span class="glyphicon glyphicon-lock">password</span>
            <input type="text" class="form-control input-sm validate[required]" name="pass" id="pass"/>
        </div>
        <br/>
        <button class="btn btn-success btn-sm" onclick="alert('test conection')">test conection</button>
        <input type="submit" class="btn btn-success btn-sm navbar-right" value="crear y cargar"/>
    </form>
</div>